services:
 mysql:
    image: mysql
    container_name: mysql
    ports:
      -"3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
       - "../mysql/conf:/etc/mysql/conf.d"
       - "../mysql/data:/var/lib/mysql"
       - "../mysql/init:/docker-entrypoint-initdb.d"
    networks:
      - airline
 airlineService:
    build:
      context: .
      dockerfile: .
    container_name: airlineService
    image: airlineService:latest
    ports:
      -"8080:8080"
    networks:
      - airline
    depends_on:
      - mysql
 nginx:
    image: nginx
    container_name: airlineNginx
    ports:
      - "18080:18080"
    networks:
      - airline
    volumes:
      - "./AirlineNginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./AirlineNginx/html:/usr/share/nginx/html"
    depends_on:
      - airlineService
 networks:
   airline:
    name: airline
    external: true
