

# server配置
server:
    port: 8080
    servlet:
        context-path: /

# 连接池配置
spring:

    application:
        name: airlineticket_idea
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            url: jdbc:mysql://localhost:3306/airline_reservations?useAffectedRows=true&rewriteBatchedStatements=true
            username: root
            password: 123456
            driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis-plus的配置
mybatis-plus:
    type-aliases-package: org.airlineticket_idea.pojo
    configuration:
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
        db-config:
            id-type: auto  # 删除或改为 auto

#jwt配置
jwt:
    token:
        tokenExpiration: 120 #有效时间,单位分钟
        tokenSignKey: justworking1234  #当前程序签名秘钥 自定义
deepseek:
    api:
        key: sk-d72585005bbf46eab454fd157c6d3450


